name: Build and run tests

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.x', '17.x', '18.x', '20.x']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dev dependencies
        run: npm i
      - name: Run linter
        run: npm run lint
      - name: Run format checker
        run: npm run format:check
      - name: Build production distribution
        run: npm run build
      - name: Run tests
        run: npm run test
